### ISSUE TITLE
IsDateSlash returns TRUE for mm/dd/yy and mm/dd/yyyy

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/dht#15]
https://github.com/degauss-org/dht/blob/9e896e5aa5a7135ef3c9928da93a86a63b1554df/R/check_dates.R#L6

if date is mm/dd/yyyy, date is not converted properly in dht::check_dates()

**Comment by cole-brokamp** [comment]
After thinking about this, I'd like to _not_ support "mm/dd/yyyy" slash format, but still support the "mm/dd/yy" slash format.  An easy implementation might be to use `strsplit(mydate, "/")` to try and ensure that all components are only two digits in length.  If one of them is greater than two, then we can complain about date formatting and error.
