### ISSUE TITLE
addresses that contain only "PO" are not filtered out

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/dht#22]
https://github.com/degauss-org/dht/blob/0f87ec511e1312f58f4e80c1c0ae5a4eb0d426be/R/address_functions.R#L27

This code only filters out addresses if "Box" is present in the string

**Comment by cole-brokamp** [comment]
I added `PO 1234 Cincinnati OH 45229` to the tests and they failed, as expected.  But after thinking how to fix this, I think we will just have to accept this as a limitation; otherwise, we run the risk of incorrectly flagging any street name that starts with "Po" as a PO Box.
