### ISSUE TITLE
LICENSE.md already exists; overwrite by running again and setting `overwrite = TRUE`

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/dht#25]
https://github.com/degauss-org/dht/blob/03e684c2e1df3e4469fd59256fc7a6f5358ea45e/R/use_degauss_files.R#L25

If another file (such as .gitignore) already exists, we get this error to set `overwrite = TRUE`. Even after setting `overwrite = TRUE`, I get the same error referencing LICENSE.md repeatedly.

**Comment by cole-brokamp** [comment]
Can you write some example code to reproduce this problem?  I'm not seeing any problems with this in our tests.

**Comment by cole-brokamp** [comment]
remove .gitignore from the template functions

also work on tests where some files may be already existing (license?) (check for all files up front rather than erroring individually)

**Comment by erikarasnick** [comment]
Started a new Rstudio project by cloning aadt github repo.
Deleted .gitignore
Ran `dht::use_degauss_container()`
Got the `renv::init()` error since we haven't merged those changes yet. 
Deleted all files created by `dht::use_degauss_container()` and restarted the R session. 

Ran `renv::init()`
installed `remotes`
installed `dht` from github
ran `dht::use_degauss_container()` and got 

`
✓ created /Users/RASV5G/OneDrive - cchmc/aadt/LICENSE.md
Error: /Users/RASV5G/OneDrive - cchmc/aadt/.dockerignore already exists
ℹ overwrite by running again and setting `overwrite = TRUE`
`

so I ran `dht::use_degauss_container(overwrite = TRUE)` but I got the exact same error.

**Comment by cole-brokamp** [comment]
maybe you forgot to remove `.dockerignore` because it is 

Can you try again with version 0.1.5?  And try in an empty folder instead of cloning at github repository first.  Not sure if that is complicating anything, but I'm not seeing the same issue with running `dht::use_degauss_container()` in a fresh directory.

But I do see the issue where it still fails when trying to run with one of the pre-existing files, even with `overwrite=TRUE`

**Comment by erikarasnick** [comment]
I don't have any problems using 0.1.5 and starting with an empty folder.

**Comment by cole-brokamp** [comment]
ok, thanks for reporting all of these!  it made it really easy to fix them!
