### ISSUE TITLE
checking for renv.lock causes use_degauss_container() to error out before all files are created

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/dht#26]
https://github.com/degauss-org/dht/blob/03e684c2e1df3e4469fd59256fc7a6f5358ea45e/R/use_degauss_files.R#L63

This stops `use_degauss_container()` after `README.md` is created, meaning the dockerfile, GHA file, makefile, and tests are not created.

**Comment by cole-brokamp** [comment]
Should we run `renv::init()` within this function directly?   I think that `renv::init()` will be okay to use even if an renv infrastructure already exists.  Then we could put in the readme that users need to do a `renv::snapshot()` before building the container with `make`

**Comment by cole-brokamp** [comment]
I decided to make it an info/warning rather than creating a project.  We will still have to make sure to document to do an `renv::init()` when making a DeGAUSS container.
