### ISSUE TITLE
update all dockerfiles to have appropriate env metadata

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/dht#53]
see `?dht::get_env_from_dockerfile` and https://github.com/degauss-org/fortunes/blob/main/Dockerfile for more information

**Comment by cole-brokamp** [comment]
@erikarasnick - do you think it is okay for me to go and add the metadata `ENV` instructions to all of the DeGAUSS Dockerfiles without doing a release?  I figure that it shouldn't change anything visible to the user and most containers will get a new version soon anyway (once we update everything to dht version 1.0).

**Comment by erikarasnick** [comment]
@cole-brokamp Yes, sounds good to me. I agree that it shouldn't change anything.

**Comment by cole-brokamp** [comment]
I did all the ones listed on degauss.org/available_images _except_ for the Schwartz images
