### ISSUE TITLE
everything in double braces doesn't show up

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/dht#67]
https://github.com/degauss-org/dht/blob/959e1c96b0526b8bfa05c549fc05bf919a1c3c29/inst/degauss_build-deploy-pr.yaml#L18

for example, when I used `dht::use_degauss_container` to populate all files, this line in my local `build-deploy-pr.yaml` file looks like this

```
container="$/$/$:latest"
```

**Comment by cole-brokamp** [comment]
can you try again with the version i just pushed up?
