### ISSUE TITLE
DeGAUSS Menu edge cases

### ISSUE THREAD

**Issue by andrew-vancil** [degauss-org/dht#80]
- Rework filtering so that data with start/end dates isn't excluded from _non_- temporal containers (eg looking for dep. index, data has start/end dates, but still show dep index container)
    - Might add a third level to the temporal column so that we have required/not permitted/optional and sort by that

**Comment by andrew-vancil** [comment]
On the 'windows_toggle' branch, I've made a couple updates:
- I separated out the "Not sure" option from the temporal data question for better filtering
    - There's a tooltip upon hovering over the question giving a little explanation
    - Basically, if you indicate that you're not sure if you have temporal, all selected containers that permit temporal columns are visible (ie the filter ignores you're selection for temporal data)
    - Right now, I have the filtering set up so that if a user *doesn't* select "not sure", then containers with a required/prohibited temporal aspect are hidden. I don't love this because if you select the not sure toggle and the census tract for "want", you will not see any containers. I'd love to discuss some better options

**Comment by cole-brokamp** [comment]
great, can you open as a PR for discussion?
