### ISSUE TITLE
Add windows toggle to DeG Menu

### ISSUE THREAD

**Issue by andrew-vancil** [degauss-org/dht#81]

**Comment by andrew-vancil** [comment]
On the 'windows_toggle' branch, I added a gear button on the table where the user can toggle Windows commands. Still working on the server side

**Comment by andrew-vancil** [comment]
Didn't we write/update one of the functions to include a windows argument? I'm having trouble finding it - do you guys @cole-brokamp @erikarasnick  remember where that ended up?

**Comment by cole-brokamp** [comment]
I thought we had done that too, but I can't find a trace of it anywhere.  I looked through all of our closed issues and PRs around the DeGAUSS Development Day we did and I couldn't see it.

I would recommend just "greping" for the `$PWD` expression in an output command and substituting in an appropriate one for the platform; e.g.

```r
gsub("$PWD", "%cd%", dht::make_degauss_command(image = "geocoder", version = "latest"), fixed = TRUE)
#> docker run --rm -v %cd%:/tmp ghcr.io/degauss-org/geocoder:latest my_address_file_geocoded.csv
```

I think this is how I originally had it in some degauss menu rshiny code.  Also how I'm specifying the temporary folder as the working directory in `degauss_run` here: 

https://github.com/degauss-org/dht/blob/1ef30471043e6330d23ccfa3f6b2685c9f72947b/R/degauss_run.R#L27

Alternatively, we could also add an argument to `make_degauss_command` that allows someone to specify the variable used for the current working directory.
