### ISSUE TITLE
updating institutional addresses

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/dht#97]
`3333 Burnett Ave CINCINNATI Ohio 45229` is geocoded to `Burnet Ave Miami Heights OH 45229`

Should we add this `Burnett` misspelling to be filtered out as an institutional address?

**Comment by cole-brokamp** [comment]
I keep struggling with how we can best support Cincinnati institutional addresses without interfering with users in other cities (e.g., 3333 Burnet Ave, Syracuse, NY 13206).

First thought is to use a DeGAUSS argument, but that is already taken for score threshold.  

How can we provide a DeGAUSS user a way to optionally filter these out without using a new argument?
